# This file was generated by GoReleaser. DO NOT EDIT.
cask "glassity" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "0df73748f7973a32dff870394333678b6fd117d266c3c023081fb3c67c5f96c7"
      url "https://github.com/glassity/cli/releases/download/v#{version}/glassity_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b35217e4b73d2d8bf8259bc39160a785cd271fa1adefd515f830cac586237a21"
      url "https://github.com/glassity/cli/releases/download/v#{version}/glassity_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bcddb5396b724f6b0767de1573794ab2bd1fca9eeab98b1a8b29e8f4dbb35876"
      url "https://github.com/glassity/cli/releases/download/v#{version}/glassity_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4987d4dfd3beb418422151c990ae40058d0a6c306f63b24572ee041af821db81"
      url "https://github.com/glassity/cli/releases/download/v#{version}/glassity_#{version}_linux_arm64.tar.gz"
    end
  end

  name "glassity"
  desc "Agent-safe command-line interface for the Glassity FinOps platform"
  homepage "https://github.com/glassity/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glassity"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glassity"]
    end
  end

  # No zap stanza required

end
