# This file was generated by GoReleaser. DO NOT EDIT.
cask "glassity" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "2d6640b32d69e4f1540ddae7e83d1abe9addc3f9914075b5c156e959e0ee0f10"
      url "https://github.com/glassity/cli/releases/download/v#{version}/glassity_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b6d69d37e48bbd69f1cb1e89e591c0317f08ba049bbdd246f10b5a6dbb6d30d5"
      url "https://github.com/glassity/cli/releases/download/v#{version}/glassity_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "344e97c4a0d363d7e7ff90a65a4cb3ded23df243e13f3f071cce29780694792c"
      url "https://github.com/glassity/cli/releases/download/v#{version}/glassity_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bade2183f576eba957cb11849280af3c963c959224e354e9854707d4e55c5145"
      url "https://github.com/glassity/cli/releases/download/v#{version}/glassity_#{version}_linux_arm64.tar.gz"
    end
  end

  name "glassity"
  desc "Agent-safe command-line interface for the Glassity FinOps platform"
  homepage "https://github.com/glassity/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glassity"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glassity"]
    end
  end

  # No zap stanza required

end
