# This file was generated by GoReleaser. DO NOT EDIT.
cask "glassity" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "e5bf32d7006af04def7ba95183f4e1b2ccd20f6582dcf5e3d146abfc0e7732cb"
      url "https://github.com/glassity/cli/releases/download/v#{version}/glassity_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5be6fbfa390dd72002ffc05be21086c474a4d1c30ed368730a752c145a21f120"
      url "https://github.com/glassity/cli/releases/download/v#{version}/glassity_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6d67dd07ac987be27da1f1c17a61b67e7057c91cbb840138c5a1b3f157fab53d"
      url "https://github.com/glassity/cli/releases/download/v#{version}/glassity_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "94d352ed0fdacb31b58bd79b43c3e39697cb503b99b27f6facb9e43bd1adab7b"
      url "https://github.com/glassity/cli/releases/download/v#{version}/glassity_#{version}_linux_arm64.tar.gz"
    end
  end

  name "glassity"
  desc "Agent-safe command-line interface for the Glassity FinOps platform"
  homepage "https://github.com/glassity/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "glassity"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/glassity"]
    end
  end

  # No zap stanza required

end
